# Generated by Django 5.1.7 on 2025-03-08 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_content', '0002_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('exercise', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypoints', to='learning_content.course')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('course', 'title')},
            },
        ),
    ]
