# Generated by Django 5.1.7 on 2025-03-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_content', '0003_keypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypoint',
            name='applications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keypoint',
            name='space_complexity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='keypoint',
            name='time_complexity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
